[package]
name = "scte35dump"
version = "0.1.0"
authors = ["David Holroyd <dave@badgers-in-foil.co.uk>"]

[dependencies]
hexdump = "0.1.0"
tokio-core = "0.1"
futures = "0.1"
mpeg2ts-reader = { path = "../mpeg2ts-reader" }
rtp-rs = { path = "../rtp-rs" }
bitreader = "0.3.1"
net2 = "0.2"
clap = "2.30.0"
hex = "0.3.1"
base64 = "0.9.0"

[profile.release]
debug = true
