[package]
name = "scte35dump"
version = "0.1.4"
authors = ["David Holroyd <dave@badgers-in-foil.co.uk>"]
description = "Dump SCTE-35 data from a Transport Stream contained within a file or RTP network stream"
repository = "https://github.com/dholroyd/scte35dump"
categories = [ "multimedia::video" ]
readme = "README.md"
license = "MIT/Apache-2.0"

[dependencies]
hexdump = "0.1.0"
mpeg2ts-reader = "0.6.0"
rtp-rs = "0.2.0"
bitreader = "0.3.1"
net2 = "0.2"
clap = "2.32"
hex = "0.3.1"
base64 = "0.9.0"
scte35-reader = "0.5.0"

[profile.release]
# for profiling,
#debug = true
